package main

import (
	"context"
	"errors"
	"fmt"
	"strings"

	"github.com/containerd/errdefs"
	"github.com/docker/docker/api/types/container"
	"github.com/docker/docker/client"
)

// DockerClient wraps the Docker SDK for easier testing.
type DockerClient interface {
	ContainerList(ctx context.Context, options container.ListOptions) ([]container.Summary, error)
	ContainerRemove(ctx context.Context, containerID string, options container.RemoveOptions) error
	Close() error
}

type realDockerClient struct {
	cli *client.Client
}

// NewDockerClient builds a Docker client using environment configuration.
func NewDockerClient() (DockerClient, error) {
	cli, err := client.NewClientWithOpts(client.FromEnv, client.WithAPIVersionNegotiation())
	if err != nil {
		return nil, fmt.Errorf("create docker client: %w", err)
	}

	return &realDockerClient{cli: cli}, nil
}

func (c *realDockerClient) ContainerList(ctx context.Context, options container.ListOptions) ([]container.Summary, error) {
	return c.cli.ContainerList(ctx, options)
}

func (c *realDockerClient) ContainerRemove(ctx context.Context, containerID string, options container.RemoveOptions) error {
	return c.cli.ContainerRemove(ctx, containerID, options)
}

func (c *realDockerClient) Close() error {
	return c.cli.Close()
}

// FindAutoGeneratedContainers returns the names of containers with autogenerated names.
func FindAutoGeneratedContainers(ctx context.Context, cli DockerClient) ([]container.Summary, error) {
	containers, err := cli.ContainerList(ctx, container.ListOptions{All: true})
	if err != nil {
		return nil, fmt.Errorf("list containers: %w", err)
	}

	found := make([]container.Summary, 0)

	for _, container := range containers {
		name := primaryContainerName(container.Names)
		if name == "" {
			continue
		}

		if IsAutoGeneratedName(name) {
			found = append(found, container)
		}
	}

	return found, nil
}

// CleanAutoGeneratedContainers deletes containers whose names come from the moby generator.
func CleanAutoGeneratedContainers(ctx context.Context, cli DockerClient) ([]string, error) {
	containers, err := cli.ContainerList(ctx, container.ListOptions{All: true})
	if err != nil {
		return nil, fmt.Errorf("list containers: %w", err)
	}

	removed := make([]string, 0)
	var removalErrors []error

	for _, c := range containers {
		name := primaryContainerName(c.Names)
		if name == "" {
			continue
		}

		if !IsAutoGeneratedName(name) {
			continue
		}

		if err := cli.ContainerRemove(ctx, c.ID, container.RemoveOptions{Force: true}); err != nil {
			if errdefs.IsNotFound(err) {
				continue
			}

			removalErrors = append(removalErrors, fmt.Errorf("remove %s (%s): %w", name, shortID(c.ID), err))
			continue
		}

		removed = append(removed, name)
	}

	if len(removalErrors) > 0 {
		return removed, errors.Join(removalErrors...)
	}

	return removed, nil
}

func primaryContainerName(names []string) string {
	if len(names) == 0 {
		return ""
	}

	return strings.TrimLeft(names[0], "/")
}

func shortID(id string) string {
	if len(id) <= 12 {
		return id
	}

	return id[:12]
}
