package main

import (
	"bufio"
	"context"
	"fmt"
	"log"
	"os"
	"strings"
)

func main() {
	ctx := context.Background()

	cli, err := NewDockerClient()
	if err != nil {
		log.Fatalf("failed to initialize docker client: %v", err)
	}
	defer cli.Close()

	// Find autogenerated containers without removing them
	candidates, err := FindAutoGeneratedContainers(ctx, cli)
	if err != nil {
		log.Fatalf("failed to find autogenerated containers: %v", err)
	}

	if len(candidates) == 0 {
		fmt.Println("No autogenerated containers found.")
		return
	}

	// Show the list
	fmt.Printf("Found %d autogenerated container(s):\n", len(candidates))
	for _, name := range candidates {
		fmt.Printf("  - %s\n", name)
	}

	// Ask for confirmation
	fmt.Print("\nDo you want to delete these containers? (yes/no): ")
	reader := bufio.NewReader(os.Stdin)
	response, err := reader.ReadString('\n')
	if err != nil {
		log.Fatalf("failed to read input: %v", err)
	}

	response = strings.TrimSpace(strings.ToLower(response))
	if response != "yes" && response != "y" {
		fmt.Println("Operation cancelled.")
		return
	}

	// Proceed with deletion
	removed, err := CleanAutoGeneratedContainers(ctx, cli)
	if err != nil {
		log.Printf("cleanup completed with errors: %v", err)
	}

	fmt.Fprintf(os.Stdout, "\nRemoved %d autogenerated container(s)\n", len(removed))
	for _, name := range removed {
		fmt.Fprintln(os.Stdout, name)
	}
}
