package main

import "testing"

func TestIsAutoGeneratedName(t *testing.T) {
	tests := []struct {
		name     string
		expected bool
	}{
		{name: "inspiring_franklin", expected: true},
		{name: "/practical_wozniak", expected: true},
		{name: "agitated_wescoff7", expected: true},
		{name: "INSPIRING_FRANKLIN", expected: true},
		{name: "custom_app", expected: false},
		{name: "loving__turing", expected: false},
		{name: "loving-turing", expected: false},
		{name: "loving_turing_extra", expected: false},
		{name: "", expected: false},
	}

	for _, tc := range tests {
		t.Run(tc.name, func(t *testing.T) {
			got := IsAutoGeneratedName(tc.name)
			if got != tc.expected {
				t.Fatalf("IsAutoGeneratedName(%q) = %v, want %v", tc.name, got, tc.expected)
			}
		})
	}
}
