package main

import (
	"regexp"
	"strings"

	_ "unsafe"

	_ "github.com/docker/docker/pkg/namesgenerator"
)

// Hack: import the namesgenerator package and link to its internal variables
// https://stackoverflow.com/a/68427392

//go:linkname left github.com/docker/docker/pkg/namesgenerator.left
var left [108]string

//go:linkname right github.com/docker/docker/pkg/namesgenerator.right
var right [236]string

var (
	adjectiveSet    map[string]struct{}
	surnameSet      map[string]struct{}
	autoNamePattern = regexp.MustCompile(`^([a-z]+)_([a-z]+)(\d+)?$`)
)

func init() {
	adjectives := make([]string, len(left))
	copy(adjectives, left[:])

	surnames := make([]string, len(right))
	copy(surnames, right[:])

	adjectiveSet = make(map[string]struct{}, len(adjectives))
	for _, adj := range adjectives {
		adjectiveSet[adj] = struct{}{}
	}

	surnameSet = make(map[string]struct{}, len(surnames))
	for _, name := range surnames {
		surnameSet[name] = struct{}{}
	}
}

// IsAutoGeneratedName reports whether the provided name follows the Docker generator format.
func IsAutoGeneratedName(name string) bool {
	trimmed := strings.TrimLeft(name, "/")
	if trimmed == "" {
		return false
	}

	candidate := strings.ToLower(trimmed)
	matches := autoNamePattern.FindStringSubmatch(candidate)
	if len(matches) == 0 {
		return false
	}

	if _, ok := adjectiveSet[matches[1]]; !ok {
		return false
	}

	if _, ok := surnameSet[matches[2]]; !ok {
		return false
	}

	return true
}
